### ISSUE TITLE
While processing files with ecmascript (for target web.browser): Invalid or unexpected token

### ISSUE THREAD

**Issue by merlinpatt** [cleverbeagle/pup#143]
Received this error on mostly fresh install of cloned Pup. The exact same code worked on someone else's computer but not mine.

```
While processing files with ecmascript (for target web.browser):
vm.js:80:10: Invalid or unexpected token
  at createScript (vm.js:80:10)
  at Object.runInThisContext (vm.js:139:10)
  at Module._compile (module.js:576:28)
  at Object.Module._extensions..js (module.js:623:10)
  at Module.load (module.js:531:32)
  at Module.Mp.load (/tools/tool-env/install-runtime.js:16:29)
  at tryModuleLoad (module.js:494:12)
  at Function.Module._load (module.js:486:3)
  at Module.require (module.js:556:17)
  at require (internal/module.js:11:18)
  at Object.<anonymous> (/Users/merlin/code/clever-beagle/tamas/node_modules/lodash/_Stack.js:6:16)
  at Module._compile (module.js:612:30)
  at Object.Module._extensions..js (module.js:623:10)
  at Module.load (module.js:531:32)
  at Module.Mp.load (/tools/tool-env/install-runtime.js:16:29)
  at tryModuleLoad (module.js:494:12)
  at Function.Module._load (module.js:486:3)
  at Module.require (module.js:556:17)
  at require (internal/module.js:11:18)
  at Object.<anonymous> (/Users/merlin/code/clever-beagle/tamas/node_modules/lodash/_baseClone.js:1:13)
  at Module._compile (module.js:612:30)
  at Object.Module._extensions..js (module.js:623:10)
  at Module.load (module.js:531:32)
  at Module.Mp.load (/tools/tool-env/install-runtime.js:16:29)
  at tryModuleLoad (module.js:494:12)
  at Function.Module._load (module.js:486:3)
  at Module.require (module.js:556:17)
  at require (internal/module.js:11:18)
  at Object.<anonymous> (/Users/merlin/code/clever-beagle/tamas/node_modules/lodash/clone.js:1:17)
  at Module._compile (module.js:612:30)
  at Object.Module._extensions..js (module.js:623:10)
  at Module.load (module.js:531:32)
  at Module.Mp.load (/tools/tool-env/install-runtime.js:16:29)
  at tryModuleLoad (module.js:494:12)
  at Function.Module._load (module.js:486:3)
  at Module.require (module.js:556:17)
  at require (internal/module.js:11:18)
  at Object.<anonymous> (/Users/merlin/code/clever-beagle/tamas/node_modules/babel-helper-builder-react-jsx/node_modules/babel-types/lib/index.js:321:14)
  at Module._compile (module.js:612:30)
  at Object.Module._extensions..js (module.js:623:10)
  at Module.load (module.js:531:32)
  at Module.Mp.load (/tools/tool-env/install-runtime.js:16:29)
  at tryModuleLoad (module.js:494:12)
  at Function.Module._load (module.js:486:3)
  at Module.require (module.js:556:17)
  at require (internal/module.js:11:18)
  at Object.<anonymous> (/Users/merlin/code/clever-beagle/tamas/node_modules/babel-helper-builder-react-jsx/lib/index.js:155:19)
  at Module._compile (module.js:612:30)
  at Object.Module._extensions..js (module.js:623:10)
  at Module.load (module.js:531:32)
  at Module.Mp.load (/tools/tool-env/install-runtime.js:16:29)
  at tryModuleLoad (module.js:494:12)
  at Function.Module._load (module.js:486:3)
  at Module.require (module.js:556:17)
  at require (internal/module.js:11:18)
  at Object.<anonymous> (/Users/merlin/code/clever-beagle/tamas/node_modules/babel-plugin-transform-react-jsx/lib/index.js:78:35)
  at Module._compile (module.js:612:30)
  at Object.Module._extensions..js (module.js:623:10)
  at Module.load (module.js:531:32)
  at Module.Mp.load (/tools/tool-env/install-runtime.js:16:29)
  at tryModuleLoad (module.js:494:12)
  at Function.Module._load (module.js:486:3)
  at Module.require (module.js:556:17)
  at require (internal/module.js:11:18)
  at Object.<anonymous> (/Users/merlin/code/clever-beagle/tamas/node_modules/babel-preset-react/lib/index.js:9:37)
  at Module._compile (module.js:612:30)
  at Object.Module._extensions..js (module.js:623:10)
  at Module.load (module.js:531:32)
  at Module.Mp.load (/tools/tool-env/install-runtime.js:16:29)
  at tryModuleLoad (module.js:494:12)
  at Function.Module._load (module.js:486:3)
  at Module.require (module.js:556:17)
  at require (internal/module.js:11:18)
  at InputFile._require (/tools/isobuild/compiler-plugin.js:386:12)
  at InputFile.require (/tools/isobuild/compiler-plugin.js:380:17)
  at requireWithPrefix (packages/babel-compiler.js:436:34)
  at requireWithPath (packages/babel-compiler.js:373:14)
  at resolveHelper (packages/babel-compiler.js:346:22)
  at packages/babel-compiler.js:322:19
  at Array.forEach (<anonymous>)
  at walkHelper (packages/babel-compiler.js:321:22)
  at walkBabelRC (packages/babel-compiler.js:311:7)
  at BabelCompiler.BCp._inferHelper (packages/babel-compiler.js:396:3)
  at BabelCompiler.BCp._inferFromBabelRc (packages/babel-compiler.js:265:17)
  at BabelCompiler.BCp.inferExtraBabelOptions (packages/babel-compiler.js:244:10)
  at BabelCompiler.BCp.processOneFileForTarget (packages/babel-compiler.js:174:10)
  at BabelCompiler.<anonymous> (packages/babel-compiler.js:111:26)
  at Array.forEach (<anonymous>)
  at BabelCompiler.BCp.processFilesForTarget (packages/babel-compiler.js:110:14)
```

**Comment by merlinpatt** [comment]
Running `meteor npm install` gives this

```
WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY: sha512-MJTUg1kjuLeQCJ+ccE4Vpa6kKVXkPYJ2mOCQyUuKLcLQsdrMCpBPUi8qVE6+YuaJkozeA9NusTAw3hLr8Xe5EQ== integrity checksum failed when using sha512: wanted sha512-MJTUg1kjuLeQCJ+ccE4Vpa6kKVXkPYJ2mOCQyUuKLcLQsdrMCpBPUi8qVE6+YuaJkozeA9NusTAw3hLr8Xe5EQ== but got sha1-wZyd+aAocC1nhhI4SmVSQExjbRU=. (15621 bytes)
WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.
WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY: sha512-oftTcaMu/EGrEIu904mWteKIv8vMuOgGYo7EhVJJN00R/EED9DCua/xxHRdYnKtcECzVg7xOWhflvJMnqcFZjw== integrity checksum failed when using sha512: wanted sha512-oftTcaMu/EGrEIu904mWteKIv8vMuOgGYo7EhVJJN00R/EED9DCua/xxHRdYnKtcECzVg7xOWhflvJMnqcFZjw== but got sha1-RJnt3NERDgshi6zy+n9/WfVcqAQ=. (52016 bytes)
WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.
WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY: sha512-yJHVQEhyqPLUTgt9B83PXu6W3rx4MvvHvSUvToogpwoGDOUQ+yDrR0HRot+yOCdCO7u4hX3pWft6kWBBcqh0UA== integrity checksum failed when using sha512: wanted sha512-yJHVQEhyqPLUTgt9B83PXu6W3rx4MvvHvSUvToogpwoGDOUQ+yDrR0HRot+yOCdCO7u4hX3pWft6kWBBcqh0UA== but got sha1-UWbihkV/AzBgZL5Ul+jbsMPTIIM=. (11423 bytes)
WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.
WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY: sha512-yIovAzMX49sF8Yl58fSCWJ5svSLuaibPxXQJFLmBObTuCr0Mf1KiPopGM9NiFjiYBCbfaa2Fh6breQ6ANVTI0A== integrity checksum failed when using sha512: wanted sha512-yIovAzMX49sF8Yl58fSCWJ5svSLuaibPxXQJFLmBObTuCr0Mf1KiPopGM9NiFjiYBCbfaa2Fh6breQ6ANVTI0A== but got sha1-pWiZ0+o8m6uHS7l3O3xe3pL0iV0=. (6301 bytes)
WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.
```

**Comment by cleverbeagle** [comment]
Hmm okay, we'll have to take a look.
