### ISSUE TITLE
New install failure

### ISSUE THREAD

**Issue by csellis** [cleverbeagle/pup#146]
Hello,
I've followed the instructions and keep getting a lodash failure on a fresh install.

Console returns:
`W20180327-16:54:15.741(-4)? (STDERR) Error: Cannot find module 'lodash.assignin'
W20180327-16:54:15.741(-4)? (STDERR)     at Function.Module._resolveFilename (module.js:513:15)
W20180327-16:54:15.741(-4)? (STDERR)     at Function.Module._load (module.js:463:25)
W20180327-16:54:15.742(-4)? (STDERR)     at Module.require (module.js:556:17)
W20180327-16:54:15.742(-4)? (STDERR)     at require (internal/module.js:11:18)
W20180327-16:54:15.743(-4)? (STDERR)     at Object.<anonymous> (/home/chris/projects/podcast/node_modules/juice/node_modules/cheerio/lib/cheerio.js:8:15)
W20180327-16:54:15.743(-4)? (STDERR)     at Module._compile (module.js:612:30)
W20180327-16:54:15.743(-4)? (STDERR)     at Object.Module._extensions..js (module.js:623:10)
W20180327-16:54:15.744(-4)? (STDERR)     at Module.load (module.js:531:32)
W20180327-16:54:15.744(-4)? (STDERR)     at tryModuleLoad (module.js:494:12)
W20180327-16:54:15.745(-4)? (STDERR)     at Function.Module._load (module.js:486:3)`

I've tried installing lodash globally after the fact.

**Comment by cleverbeagle** [comment]
Hi @csellis have you run a `meteor npm install` after cloning the project?

**Comment by csellis** [comment]
Yes I have. I also followed the instructions on [http://forum.cleverbeagle.com/t/errors-after-doing-a-brand-new-install-on-mac-osx/144/6](url) to no avail. I have updated to Meteor 1.6.1 since the original to post. Now I'm getting the following in the browser:

```
Errors prevented startup:

While processing files with ecmascript (for target web.browser):
/home/chris/projects/podcast/node_modules/babel-plugin-lodash/lib/index.js:105:49: Cannot read property 'imports' of undefined
  at PluginPass.Program (/home/chris/projects/podcast/node_modules/babel-plugin-lodash/lib/index.js:105:49)
  at newFn (/home/chris/.meteor/packages/ecmascript/.0.10.0.19ijgm3.er78++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/traverse/lib/visitors.js:223:21)
  at NodePath._call (/home/chris/.meteor/packages/ecmascript/.0.10.0.19ijgm3.er78++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/traverse/lib/path/context.js:64:19)
  at NodePath.call (/home/chris/.meteor/packages/ecmascript/.0.10.0.19ijgm3.er78++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/traverse/lib/path/context.js:38:17)
  at NodePath.visit (/home/chris/.meteor/packages/ecmascript/.0.10.0.19ijgm3.er78++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/traverse/lib/path/context.js:99:12)
  at TraversalContext.visitQueue (/home/chris/.meteor/packages/ecmascript/.0.10.0.19ijgm3.er78++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/traverse/lib/context.js:139:18)
  at TraversalContext.visitSingle (/home/chris/.meteor/packages/ecmascript/.0.10.0.19ijgm3.er78++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/traverse/lib/context.js:98:19)
  at TraversalContext.visit (/home/chris/.meteor/packages/ecmascript/.0.10.0.19ijgm3.er78++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/traverse/lib/context.js:180:19)
  at Function.traverse.node (/home/chris/.meteor/packages/ecmascript/.0.10.0.19ijgm3.er78++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/traverse/lib/index.js:76:17)
  at traverse (/home/chris/.meteor/packages/ecmascript/.0.10.0.19ijgm3.er78++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/traverse/lib/index.js:46:12)
  at transformFile (/home/chris/.meteor/packages/ecmascript/.0.10.0.19ijgm3.er78++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/core/lib/transformation/index.js:107:27)
  at runSync (/home/chris/.meteor/packages/ecmascript/.0.10.0.19ijgm3.er78++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/core/lib/transformation/index.js:35:3)
  at transformFromAstSync (/home/chris/.meteor/packages/ecmascript/.0.10.0.19ijgm3.er78++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/core/lib/transform-ast-sync.js:16:38)
  at Object.transformFromAst (/home/chris/.meteor/packages/ecmascript/.0.10.0.19ijgm3.er78++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/core/lib/transform-ast.js:20:68)
  at transform (/home/chris/.meteor/packages/ecmascript/.0.10.0.19ijgm3.er78++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/index.js:71:30)
  at compile (/home/chris/.meteor/packages/ecmascript/.0.10.0.19ijgm3.er78++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/index.js:82:14)
  at Cache.Cp.get (/home/chris/.meteor/packages/ecmascript/.0.10.0.19ijgm3.er78++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/cache.js:101:26)
  at Object.compile (/home/chris/.meteor/packages/ecmascript/.0.10.0.19ijgm3.er78++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/index.js:46:23)
  at Object.compile (packages/babel-compiler.js:51:29)
  at packages/babel-compiler.js:186:22
  at Function.time (/tools/tool-env/profile.js:305:10)
  at profile (packages/babel-compiler.js:229:20)
  at BabelCompiler.BCp.processOneFileForTarget (packages/babel-compiler.js:185:20)
  at BabelCompiler.<anonymous> (packages/babel-compiler.js:111:26)
  at Array.forEach (<anonymous>)
  at BabelCompiler.BCp.processFilesForTarget (packages/babel-compiler.js:110:14)


While processing files with ecmascript (for target os.linux.x86_64):
/home/chris/projects/podcast/node_modules/babel-plugin-lodash/lib/index.js:105:49: Cannot read property 'imports' of undefined
  at PluginPass.Program (/home/chris/projects/podcast/node_modules/babel-plugin-lodash/lib/index.js:105:49)
  at newFn (/home/chris/.meteor/packages/ecmascript/.0.10.0.19ijgm3.er78++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/traverse/lib/visitors.js:223:21)
  at NodePath._call (/home/chris/.meteor/packages/ecmascript/.0.10.0.19ijgm3.er78++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/traverse/lib/path/context.js:64:19)
  at NodePath.call (/home/chris/.meteor/packages/ecmascript/.0.10.0.19ijgm3.er78++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/traverse/lib/path/context.js:38:17)
  at NodePath.visit (/home/chris/.meteor/packages/ecmascript/.0.10.0.19ijgm3.er78++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/traverse/lib/path/context.js:99:12)
  at TraversalContext.visitQueue (/home/chris/.meteor/packages/ecmascript/.0.10.0.19ijgm3.er78++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/traverse/lib/context.js:139:18)
  at TraversalContext.visitSingle (/home/chris/.meteor/packages/ecmascript/.0.10.0.19ijgm3.er78++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/traverse/lib/context.js:98:19)
  at TraversalContext.visit (/home/chris/.meteor/packages/ecmascript/.0.10.0.19ijgm3.er78++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/traverse/lib/context.js:180:19)
  at Function.traverse.node (/home/chris/.meteor/packages/ecmascript/.0.10.0.19ijgm3.er78++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/traverse/lib/index.js:76:17)
  at traverse (/home/chris/.meteor/packages/ecmascript/.0.10.0.19ijgm3.er78++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/traverse/lib/index.js:46:12)
  at transformFile (/home/chris/.meteor/packages/ecmascript/.0.10.0.19ijgm3.er78++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/core/lib/transformation/index.js:107:27)
  at runSync (/home/chris/.meteor/packages/ecmascript/.0.10.0.19ijgm3.er78++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/core/lib/transformation/index.js:35:3)
  at transformFromAstSync (/home/chris/.meteor/packages/ecmascript/.0.10.0.19ijgm3.er78++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/core/lib/transform-ast-sync.js:16:38)
  at Object.transformFromAst (/home/chris/.meteor/packages/ecmascript/.0.10.0.19ijgm3.er78++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/core/lib/transform-ast.js:20:68)
  at transform (/home/chris/.meteor/packages/ecmascript/.0.10.0.19ijgm3.er78++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/index.js:71:30)
  at compile (/home/chris/.meteor/packages/ecmascript/.0.10.0.19ijgm3.er78++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/index.js:82:14)
  at Cache.Cp.get (/home/chris/.meteor/packages/ecmascript/.0.10.0.19ijgm3.er78++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/cache.js:101:26)
  at Object.compile (/home/chris/.meteor/packages/ecmascript/.0.10.0.19ijgm3.er78++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/index.js:46:23)
  at Object.compile (packages/babel-compiler.js:51:29)
  at packages/babel-compiler.js:186:22
  at Function.time (/tools/tool-env/profile.js:305:10)
  at profile (packages/babel-compiler.js:229:20)
  at BabelCompiler.BCp.processOneFileForTarget (packages/babel-compiler.js:185:20)
  at BabelCompiler.<anonymous> (packages/babel-compiler.js:111:26)
  at Array.forEach (<anonymous>)
  at BabelCompiler.BCp.processFilesForTarget (packages/babel-compiler.js:110:14)


Your application has errors. Waiting for file change.
Started MongoDB.
```

**Comment by cleverbeagle** [comment]
@csellis does it work if you downgrade Meteor to 1.6.0? You can try this by opening up the `.meteor/release` file at the root of your project and changing the version to 1.6.0. When you restart the app, Meteor will detect this and switch to that version.

I ask this because we've had a few folks mention issue with 1.6.1 and Meteor made some changes to Babel which seems to be tripping up our dependencies.

**Comment by csellis** [comment]
It doesn't. That's what I had installed at first.

**Comment by cleverbeagle** [comment]
Hey @csellis sorry this is causing so much trouble. Looking into this further, a possible fix:

1. Run a `meteor update` to bring Meteor up to the latest version.
2. Delete the `.babelrc` file at the root of the project.
3. Run `meteor npm i --save @babel/runtime`.
4. Boot the project.

Can confirm that following an update to `METEOR@1.6.1`, I received an error similar to what you saw above. Following the steps above resolved the errors.

**Comment by csellis** [comment]
Hi @cleverbeagle , it's still not working. I'm going to try a fresh install.

**Comment by csellis** [comment]
@cleverbeagle, fresh install did it. After deleting .babelrc and reinstalling. Not sure why the first one wouldn't work.

**Comment by pjbrow** [comment]
@cleverbeagle Using Pup v1.4.0 I had exactly the same error as @csellis.  Can confirm that your instructions worked to fix the issue.  Looking forward to cleaner syntax with Babel 7!

**Comment by Bandit** [comment]
Same. Running `meteor npm i --save @babel/runtime` worked after deleting `.babelrc`
