### ISSUE TITLE
npm run has some problem

### ISSUE THREAD

**Issue by Here21** [cleverbeagle/pup#18]
I complete following the "Getting Started", but when I get to `npm start`, I saw the following information.

```
 npm start

> pup@ start /Users/simon/workspace/MyProject/MakerLab
> meteor --settings settings-development.json

[[[[[ ~/workspace/MyProject/MakerLab ]]]]]    

=> Started proxy.                             
=> Started MongoDB.                           
=> Errors prevented startup:                  
   
   While loading package fourseven:scss@4.5.4:
   error: Command failed: /Users/simon/.meteor/packages/meteor-tool/.1.5.0.17ci6hi++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm rebuild --update-binary
   Cannot download "https://github.com/sass/node-sass/releases/download/v4.5.3/darwin-x64-46_binding.node": 
   
   socket hang up
   
   Hint: If github.com is not accessible in your location
   try setting a proxy via HTTP_PROXY, e.g. 
   
   export HTTP_PROXY=http://example.com:1234
   
   or configure npm proxy via
   
   npm config set proxy http://example.com:8080
   gyp info it worked if it ends with ok
   gyp verb cli [ '/Users/simon/.meteor/packages/meteor-tool/.1.5.0.17ci6hi++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node',
   gyp verb cli   '/Users/simon/.meteor/packages/fourseven_scss/.4.5.4.7ue0g6++os+web.browser+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/node-gyp/bin/node-gyp.js',
   gyp verb cli   'rebuild',
   gyp verb cli   '--verbose',
   gyp verb cli   '--libsass_ext=',
   gyp verb cli   '--libsass_cflags=',
   gyp verb cli   '--libsass_ldflags=',
   gyp verb cli   '--libsass_library=' ]
   gyp info using node-gyp@3.6.2
   gyp info using node@4.8.3 | darwin | x64
   gyp verb command rebuild []
   gyp verb command clean []
   gyp verb clean removing "build" directory
   gyp verb command configure []
   gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
   gyp verb download using dist-url https://nodejs.org/dist
   gyp verb check python checking for Python executable "python2" in the PATH
   gyp ERR! UNCAUGHT EXCEPTION 
   gyp ERR! stack TypeError: Property description must be an object: Error: not found: python2
   gyp ERR! stack     at getNotFoundError
   (/Users/simon/.meteor/packages/fourseven_scss/.4.5.4.7ue0g6++os+web.browser+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/which/which.js:13:12)
   gyp ERR! stack     at F (/Users/simon/.meteor/packages/fourseven_scss/.4.5.4.7ue0g6++os+web.browser+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/which/which.js:68:19)
   gyp ERR! stack     at E (/Users/simon/.meteor/packages/fourseven_scss/.4.5.4.7ue0g6++os+web.browser+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/which/which.js:80:29)
   gyp ERR! stack     at /Users/simon/.meteor/packages/fourseven_scss/.4.5.4.7ue0g6++os+web.browser+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/which/which.js:89:16
   gyp ERR! stack     at /Users/simon/.meteor/packages/fourseven_scss/.4.5.4.7ue0g6++os+web.browser+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/isexe/index.js:42:5
   gyp ERR! stack     at /Users/simon/.meteor/packages/fourseven_scss/.4.5.4.7ue0g6++os+web.browser+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/isexe/mode.js:8:5
   gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
   gyp ERR! stack     at Function.defineProperty (native)
   gyp ERR! stack     at EventEmitter.<anonymous>
   (/Users/simon/.meteor/packages/fourseven_scss/.4.5.4.7ue0g6++os+web.browser+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/npmlog/log.js:185:14)
   gyp ERR! stack     at EventEmitter.<anonymous>
   (/Users/simon/.meteor/packages/fourseven_scss/.4.5.4.7ue0g6++os+web.browser+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/npmlog/log.js:281:23)
   gyp ERR! stack     at Object.<anonymous>
   (/Users/simon/.meteor/packages/fourseven_scss/.4.5.4.7ue0g6++os+web.browser+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/node-gyp/lib/configure.js:389:18)
   gyp ERR! stack     at F (/Users/simon/.meteor/packages/fourseven_scss/.4.5.4.7ue0g6++os+web.browser+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/which/which.js:68:16)
   gyp ERR! stack     at E (/Users/simon/.meteor/packages/fourseven_scss/.4.5.4.7ue0g6++os+web.browser+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/which/which.js:80:29)
   gyp ERR! stack     at /Users/simon/.meteor/packages/fourseven_scss/.4.5.4.7ue0g6++os+web.browser+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/which/which.js:89:16
   gyp ERR! stack     at /Users/simon/.meteor/packages/fourseven_scss/.4.5.4.7ue0g6++os+web.browser+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/isexe/index.js:42:5
   gyp ERR! stack     at /Users/simon/.meteor/packages/fourseven_scss/.4.5.4.7ue0g6++os+web.browser+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/isexe/mode.js:8:5
   gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
   gyp ERR! System Darwin 16.6.0
   gyp ERR! command "/Users/simon/.meteor/packages/meteor-tool/.1.5.0.17ci6hi++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node"
   "/Users/simon/.meteor/packages/fourseven_scss/.4.5.4.7ue0g6++os+web.browser+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose"
   "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
   gyp ERR! cwd /Users/simon/.meteor/packages/fourseven_scss/.4.5.4.7ue0g6++os+web.browser+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/.temp-1rbbfhm/node_modules/node-sass
   gyp ERR! node -v v4.8.3
   gyp ERR! node-gyp -v v3.6.2
   gyp ERR! This is a bug in `node-gyp`.
   gyp ERR! Try to update node-gyp and file an Issue if it does not help:
   gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
   Build failed with error code: 7
   npm ERR! code ELIFECYCLE
   npm ERR! errno 1
   npm ERR! node-sass@4.5.3 postinstall: `node scripts/build.js`
   npm ERR! Exit status 1
   npm ERR! 
   npm ERR! Failed at the node-sass@4.5.3 postinstall script.
   npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
   
   npm ERR! A complete log of this run can be found in:
   npm ERR!     /Users/simon/.npm/_logs/2017-07-12T14_29_12_877Z-debug.log
   Cannot download "https://github.com/sass/node-sass/releases/download/v4.5.3/darwin-x64-46_binding.node": 
   
   socket hang up
   
   Hint: If github.com is not accessible in your location
   try setting a proxy via HTTP_PROXY, e.g. 
   
   export HTTP_PROXY=http://example.com:1234
   
   or configure npm proxy via
   
   npm config set proxy http://example.com:8080
   gyp info it worked if it ends with ok
   gyp verb cli [ '/Users/simon/.meteor/packages/meteor-tool/.1.5.0.17ci6hi++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node',
   gyp verb cli   '/Users/simon/.meteor/packages/fourseven_scss/.4.5.4.7ue0g6++os+web.browser+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/node-gyp/bin/node-gyp.js',
   gyp verb cli   'rebuild',
   gyp verb cli   '--verbose',
   gyp verb cli   '--libsass_ext=',
   gyp verb cli   '--libsass_cflags=',
   gyp verb cli   '--libsass_ldflags=',
   gyp verb cli   '--libsass_library=' ]
   gyp info using node-gyp@3.6.2
   gyp info using node@4.8.3 | darwin | x64
   gyp verb command rebuild []
   gyp verb command clean []
   gyp verb clean removing "build" directory
   gyp verb command configure []
   gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
   gyp verb download using dist-url https://nodejs.org/dist
   gyp verb check python checking for Python executable "python2" in the PATH
   gyp ERR! UNCAUGHT EXCEPTION 
   gyp ERR! stack TypeError: Property description must be an object: Error: not found: python2
   gyp ERR! stack     at getNotFoundError
   (/Users/simon/.meteor/packages/fourseven_scss/.4.5.4.7ue0g6++os+web.browser+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/which/which.js:13:12)
   gyp ERR! stack     at F (/Users/simon/.meteor/packages/fourseven_scss/.4.5.4.7ue0g6++os+web.browser+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/which/which.js:68:19)
   gyp ERR! stack     at E (/Users/simon/.meteor/packages/fourseven_scss/.4.5.4.7ue0g6++os+web.browser+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/which/which.js:80:29)
   gyp ERR! stack     at /Users/simon/.meteor/packages/fourseven_scss/.4.5.4.7ue0g6++os+web.browser+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/which/which.js:89:16
   gyp ERR! stack     at /Users/simon/.meteor/packages/fourseven_scss/.4.5.4.7ue0g6++os+web.browser+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/isexe/index.js:42:5
   gyp ERR! stack     at /Users/simon/.meteor/packages/fourseven_scss/.4.5.4.7ue0g6++os+web.browser+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/isexe/mode.js:8:5
   gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
   gyp ERR! stack     at Function.defineProperty (native)
   gyp ERR! stack     at EventEmitter.<anonymous>
   (/Users/simon/.meteor/packages/fourseven_scss/.4.5.4.7ue0g6++os+web.browser+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/npmlog/log.js:185:14)
   gyp ERR! stack     at EventEmitter.<anonymous>
   (/Users/simon/.meteor/packages/fourseven_scss/.4.5.4.7ue0g6++os+web.browser+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/npmlog/log.js:281:23)
   gyp ERR! stack     at Object.<anonymous>
   (/Users/simon/.meteor/packages/fourseven_scss/.4.5.4.7ue0g6++os+web.browser+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/node-gyp/lib/configure.js:389:18)
   gyp ERR! stack     at F (/Users/simon/.meteor/packages/fourseven_scss/.4.5.4.7ue0g6++os+web.browser+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/which/which.js:68:16)
   gyp ERR! stack     at E (/Users/simon/.meteor/packages/fourseven_scss/.4.5.4.7ue0g6++os+web.browser+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/which/which.js:80:29)
   gyp ERR! stack     at /Users/simon/.meteor/packages/fourseven_scss/.4.5.4.7ue0g6++os+web.browser+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/which/which.js:89:16
   gyp ERR! stack     at /Users/simon/.meteor/packages/fourseven_scss/.4.5.4.7ue0g6++os+web.browser+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/isexe/index.js:42:5
   gyp ERR! stack     at /Users/simon/.meteor/packages/fourseven_scss/.4.5.4.7ue0g6++os+web.browser+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/isexe/mode.js:8:5
   gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
   gyp ERR! System Darwin 16.6.0
   gyp ERR! command "/Users/simon/.meteor/packages/meteor-tool/.1.5.0.17ci6hi++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node"
   "/Users/simon/.meteor/packages/fourseven_scss/.4.5.4.7ue0g6++os+web.browser+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose"
   "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
   gyp ERR! cwd /Users/simon/.meteor/packages/fourseven_scss/.4.5.4.7ue0g6++os+web.browser+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/.temp-1rbbfhm/node_modules/node-sass
   gyp ERR! node -v v4.8.3
   gyp ERR! node-gyp -v v3.6.2
   gyp ERR! This is a bug in `node-gyp`.
   gyp ERR! Try to update node-gyp and file an Issue if it does not help:
   gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
   Build failed with error code: 7
   npm ERR! code ELIFECYCLE
   npm ERR! errno 1
   npm ERR! node-sass@4.5.3 postinstall: `node scripts/build.js`
   npm ERR! Exit status 1
   npm ERR! 
   npm ERR! Failed at the node-sass@4.5.3 postinstall script.
   npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
   
   npm ERR! A complete log of this run can be found in:
   npm ERR!     /Users/simon/.npm/_logs/2017-07-12T14_29_12_877Z-debug.log
   
   
=> Your application has errors. Waiting for file change.
                                              

```

**Comment by cleverbeagle** [comment]
@Here21 this seems to be a network error when trying to download one of Pup's dependencies:

```
   socket hang up
   
   Hint: If github.com is not accessible in your location
   try setting a proxy via HTTP_PROXY, e.g. 
   
   export HTTP_PROXY=http://example.com:1234
   
   or configure npm proxy via
 ```

It's worth trying the startup process again. If it doesn't work, it may be worth trying the `HTTP_PROXY` flag specified here. If you keep having trouble, let me know.
