### ISSUE TITLE
Fresh install on Ubuntu 18.04 does not seem to work

### ISSUE THREAD

**Issue by exilef** [cleverbeagle/pup#268]
Hi,

I cloned the latest pup at commit 9bbffd86ec28fbfd87c0fa2aa1079971f3f74d58 and followed [the install instructions](https://cleverbeagle.com/pup/v2/cloning-installing-dependencies) - but somehow I cannot get it to run, it crashes with an error when I start it with `meteor run` (see below). Steps performed:

1. On a fresh Ubuntu 18.04 I first installed Meteor 1.8 with `curl https://install.meteor.com/ | sh`.
2. I then cloned `pup`:  `git clone https://github.com/cleverbeagle/pup.git && cd pup`
3. Installed dependencies `meteor npm install`
4. Started the instance `meteor run`

Upon running `meteor run`, Meteor builds the app, but then crashes:

```
W20181114-05:31:31.825(0)? (STDERR) [Pup] Woof! OAuth settings are not configured. OAuth login will not function. See https://cleverbeagle.com/pup/v2/accounts/oauth#setting-oauth-credentials for configuration instructions.
W20181114-05:31:32.145(0)? (STDERR) /home/vagrant/.meteor/packages/promise/.0.11.1.lt6vo5.rl7ft++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/promise_server.js:218
W20181114-05:31:32.146(0)? (STDERR)       throw error;
W20181114-05:31:32.147(0)? (STDERR)       ^
W20181114-05:31:32.147(0)? (STDERR)
W20181114-05:31:32.148(0)? (STDERR) TypeError: Cannot read property 'supportEmail' of undefined
W20181114-05:31:32.149(0)? (STDERR)     at emailTemplates.js (startup/server/accounts/emailTemplates.js:13:47)
W20181114-05:31:32.150(0)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:336:7)
W20181114-05:31:32.150(0)? (STDERR)     at Module.require (packages/modules-runtime.js:238:14)
W20181114-05:31:32.151(0)? (STDERR)     at Module.moduleLink [as link] (/home/vagrant/.meteor/packages/modules/.0.13.0.v7rrc0.mq6ad++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/reify/lib/runtime/index.js:38:38)
W20181114-05:31:32.152(0)? (STDERR)     at index.js (startup/server/accounts/index.js:1:61)
W20181114-05:31:32.152(0)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:336:7)
W20181114-05:31:32.153(0)? (STDERR)     at Module.require (packages/modules-runtime.js:238:14)
W20181114-05:31:32.154(0)? (STDERR)     at Module.moduleLink [as link] (/home/vagrant/.meteor/packages/modules/.0.13.0.v7rrc0.mq6ad++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/reify/lib/runtime/index.js:38:38)
W20181114-05:31:32.154(0)? (STDERR)     at index.js (startup/server/index.js:1:8)
W20181114-05:31:32.155(0)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:336:7)
W20181114-05:31:32.156(0)? (STDERR)     at Module.require (packages/modules-runtime.js:238:14)
W20181114-05:31:32.156(0)? (STDERR)     at require (packages/modules-runtime.js:258:21)
W20181114-05:31:32.157(0)? (STDERR)     at /home/vagrant/pup/.meteor/local/build/programs/server/app/app.js:12395:15
W20181114-05:31:32.158(0)? (STDERR)     at infos.forEach.info (/home/vagrant/pup/.meteor/local/build/programs/server/boot.js:418:13)
W20181114-05:31:32.159(0)? (STDERR)     at Array.forEach (<anonymous>)
W20181114-05:31:32.159(0)? (STDERR)     at /home/vagrant/pup/.meteor/local/build/programs/server/boot.js:417:9
W20181114-05:31:32.160(0)? (STDERR)     at /home/vagrant/pup/.meteor/local/build/programs/server/boot.js:471:5
W20181114-05:31:32.161(0)? (STDERR)     at Function.run (/home/vagrant/pup/.meteor/local/build/programs/server/profile.js:510:12)
W20181114-05:31:32.161(0)? (STDERR)     at /home/vagrant/pup/.meteor/local/build/programs/server/boot.js:470:11
```

Any help how I can get it to work? Do I have to set some more configuration variables maybe?

**Comment by Falkovic1993** [comment]
Hi @exilef, I guess you just want it to run on localhost right? 

Can't remember if it's something the pup team changed from version 1, but try using the command `npm run dev` to run it locally.

I believe meteor run will try to run it either on staging or production which fails because you need to configure it with your own settings before doing that.

**Comment by exilef** [comment]
That worked, thanks!!
