### ISSUE TITLE
deployment issue

### ISSUE THREAD

**Issue by sw-yx** [cleverbeagle/pup#9]
trying to deploy Pup to heroku and i got this error:

```
2017-06-21T06:12:21.023519+00:00 heroku[web.1]: Starting process with command `.meteor/heroku_build/bin/node $NODEJS_PARAMS .meteor/heroku_build/app/main.js`
2017-06-21T06:12:24.740982+00:00 app[web.1]: /app/.meteor/heroku_build/app/programs/server/node_modules/fibers/future.js:280
2017-06-21T06:12:24.741010+00:00 app[web.1]: 						throw(ex);
2017-06-21T06:12:24.741023+00:00 app[web.1]: 						^
2017-06-21T06:12:24.741025+00:00 app[web.1]: 
2017-06-21T06:12:24.741032+00:00 app[web.1]: TypeError: Cannot read property 'OAuth' of undefined
2017-06-21T06:12:24.741039+00:00 app[web.1]:     at meteorInstall.imports.startup.server.accounts.oauth.js (imports/startup/server/accounts/oauth.js:4:23)
2017-06-21T06:12:24.741040+00:00 app[web.1]:     at fileEvaluate (packages/modules-runtime.js:333:9)
2017-06-21T06:12:24.741040+00:00 app[web.1]:     at require (packages/modules-runtime.js:228:16)
2017-06-21T06:12:24.741041+00:00 app[web.1]:     at meteorInstall.imports.startup.server.accounts.index.js (imports/startup/server/accounts/index.js:1:14)
2017-06-21T06:12:24.741042+00:00 app[web.1]:     at fileEvaluate (packages/modules-runtime.js:333:9)
2017-06-21T06:12:24.741042+00:00 app[web.1]:     at require (packages/modules-runtime.js:228:16)
2017-06-21T06:12:24.741049+00:00 app[web.1]:     at meteorInstall.imports.startup.server.index.js (imports/startup/server/index.js:1:14)
2017-06-21T06:12:24.741050+00:00 app[web.1]:     at fileEvaluate (packages/modules-runtime.js:333:9)
2017-06-21T06:12:24.741050+00:00 app[web.1]:     at require (packages/modules-runtime.js:228:16)
2017-06-21T06:12:24.741051+00:00 app[web.1]:     at meteorInstall.server.main.js (server/main.js:1:14)
2017-06-21T06:12:24.850781+00:00 heroku[web.1]: State changed from starting to crashed
2017-06-21T06:12:24.843187+00:00 heroku[web.1]: Process exited with status 1
```

even though i have set my `settings-production.json` file it is running into this ugly error. what else is causing this issue?

**Comment by sw-yx** [comment]
in case it matters, i am using this buildpack: https://github.com/AdmitHub/meteor-buildpack-horse

**Comment by Davidlab** [comment]
You need to start Meteor with `npm start` which will in return will call the command `meteor --settings settings-development.json` from the start script in your package.json file. This will set the value of 'OAuth' during startup.

**Comment by sw-yx** [comment]
thats obviously only for running it in dev on local machine right? what about when i need to run it in production on heroku. that is what i call deployment.

**Comment by justin88** [comment]
Did you write your own settings-production.json?  See details here:

- http://cleverbeagle.com/pup/v1/the-basics/settings
- http://cleverbeagle.com/pup/v1/file-structure

**Comment by sw-yx** [comment]
hello, yes, i did write my own settings-production.json. however it seemed like it wasnt deploying correctly on heroku. i havent managed to figure out how to fix it the "correct" way but i have commented out the oauth check for now in pup.

**Comment by joserocha3** [comment]
@sw-yx did you add a config variable for METEOR_SETTINGS to your app on the heroku dashboard?

Choose your app -> settings -> reveal config vars ->  add METEOR_SETTINGS and paste in the json from your settings file

![screenshot_20170625-210543](https://user-images.githubusercontent.com/11415340/27522256-30239882-59ea-11e7-8137-45e86e410c6a.png)

**Comment by joserocha3** [comment]
On a side note, of you are not going to enter oauth values the set your METEOR_SETTINGS to this. That will avoid the oauth buttons from getting a setup.

`{
  "private": {
  },
  "public" :{
  }
}`

**Comment by sw-yx** [comment]
ahh. i will try this. this sounds very promising. thanks very much @joserocha3, closing for now. may want to put this (Heroku deployment notes) somewhere in the docs (maybe its obvious and i'm just a newbie).
