### ISSUE TITLE
I can't install...

### ISSUE THREAD

**Issue by nickwild-999** [cleverbeagle/pup#90]
I get an error...

Any thoughts?

```
module.js:529
    throw err;
    ^

Error: Cannot find module 'semver'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/unsupported.js:2:14)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
```

**Comment by nickwild-999** [comment]
I have tried again and noticed it has an error...

`npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!`

there was a quick flash about a fall back and then...

```
Update available 4.6.1 → 5.5.1    │
   │     Run npm i -g npm to update
```


This does not run and has the same semver error

**Comment by nickwild-999** [comment]
I reinstalled node but LTS version this time and it worked

**Comment by tomscholz** [comment]
Quick tip: Use a node version manager to quickly switch between node versions :)

https://github.com/tj/n (osx)
https://github.com/coreybutler/nvm-windows (windows)
https://github.com/creationix/nvm (osx)

**Comment by nickwild-999** [comment]
Very frustrating I don't think I changed anything, but it has stopped working throwing this error

```
20171030-08:42:42.191(0)? (STDERR) /Users/nickwild/.meteor/packages/meteor-tool/.1.5.2_2.1899z8d++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20171030-08:42:42.239(0)? (STDERR) 						throw(ex);
W20171030-08:42:42.240(0)? (STDERR) 						^
W20171030-08:42:42.241(0)? (STDERR)
W20171030-08:42:42.242(0)? (STDERR) TypeError: Cannot read property 'OAuth' of undefined
W20171030-08:42:42.242(0)? (STDERR)     at meteorInstall.imports.startup.server.accounts.oauth.js (imports/startup/server/accounts/oauth.js:4:23)
W20171030-08:42:42.243(0)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:333:9)
W20171030-08:42:42.244(0)? (STDERR)     at require (packages/modules-runtime.js:228:16)
W20171030-08:42:42.244(0)? (STDERR)     at meteorInstall.imports.startup.server.accounts.index.js (imports/startup/server/accounts/index.js:1:14)
W20171030-08:42:42.245(0)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:333:9)
W20171030-08:42:42.245(0)? (STDERR)     at require (packages/modules-runtime.js:228:16)
W20171030-08:42:42.246(0)? (STDERR)     at meteorInstall.imports.startup.server.index.js (imports/startup/server/index.js:1:14)
W20171030-08:42:42.246(0)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:333:9)
W20171030-08:42:42.247(0)? (STDERR)     at require (packages/modules-runtime.js:228:16)
W20171030-08:42:42.247(0)? (STDERR)     at meteorInstall.server.main.js (server/main.js:1:14)
```
It mentioned that I needed to install the 1.5.5.2. tried a new install and it didn't work also tried reinstalling and doing a meteor upgrade all to no avail. No idea why it stopped working -  any ideas anyone?

Thanks

**Comment by cleverbeagle** [comment]
@nickwild-999 this looks like a different error. Make sure that when you start the app up, you include the settings file (this is handled automatically for you with `meteor npm start`, or, can be done manually with `meteor --settings settings-development.json`).

**Comment by nickwild-999** [comment]
Oops!! So sorry. I was flipping between different Meteor installs and didn't include npm start!

**Comment by cleverbeagle** [comment]
@nickwild-999 no worries, glad to hear it's working :)
