### ISSUE TITLE
Error: Cannot find module './utils.js' when running npm start

### ISSUE THREAD

**Issue by stevenqzhang** [cleverbeagle/pup#98]
I'm at commit 33813dd  

When I do `meteor npm install` followed by `npm start`, I get this error:

```
W20171107-12:15:46.180(-5)? (STDERR) /Users/steven/dev_local/pup/.meteor/local/build/programs/server/boot.js:391
W20171107-12:15:46.184(-5)? (STDERR) }).run();
W20171107-12:15:46.185(-5)? (STDERR)    ^
W20171107-12:15:46.187(-5)? (STDERR)
W20171107-12:15:46.188(-5)? (STDERR) Error: Cannot find module './utils.js'
W20171107-12:15:46.190(-5)? (STDERR)     at makeMissingError (packages/modules-runtime.js:221:12)
W20171107-12:15:46.191(-5)? (STDERR)     at require (packages/modules-runtime.js:231:19)
W20171107-12:15:46.193(-5)? (STDERR)     at meteorInstall.node_modules.meteor.modules.node_modules.reify.lib.runtime.index.js (packages/modules.js:225:13)
W20171107-12:15:46.194(-5)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:333:9)
W20171107-12:15:46.195(-5)? (STDERR)     at require (packages/modules-runtime.js:228:16)
W20171107-12:15:46.198(-5)? (STDERR)     at meteorInstall.node_modules.meteor.modules.reify.js (packages/modules.js:204:1)
W20171107-12:15:46.199(-5)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:333:9)
W20171107-12:15:46.201(-5)? (STDERR)     at require (packages/modules-runtime.js:228:16)
W20171107-12:15:46.205(-5)? (STDERR)     at meteorInstall.node_modules.meteor.modules.server.js (packages/modules.js:19:1)
W20171107-12:15:46.205(-5)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:333:9)
=> Exited with code: 1
```

Same thing happens if I run `meteor npm start`

**Comment by stevenqzhang** [comment]
After doing a clean meteor install and clean clone of pup, I no longer get this issue
